Organizations:
    - &chainz1
        Name: chainz1
        ID: chainz1
        MSPDir: crypto-config/ordererOrganizations/chainz1/msp
    - &chainz2
        Name: chainz2
        ID: chainz2
        MSPDir: crypto-config/ordererOrganizations/chainz2/msp
    - &skcc
        Name: skcc
        ID: skcc
        MSPDir: crypto-config/peerOrganizations/skcc/msp
        AnchorPeers:
            - Host: skcc_peer2
              Port: 8051
    - &contractor1
        Name: contractor1
        ID: contractor1
        MSPDir: crypto-config/peerOrganizations/contractor1/msp
        AnchorPeers:
            - Host: contractor1_peer2
              Port: 11051

Orderer: &raft
    OrdererType: etcdraft
    Addresses:
        - chainz1_orderer1:6050
        - chainz1_orderer2:7050
        - chainz2_orderer1:8050
        - chainz2_orderer2:9050
    BatchTimeout: 1s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    EtcdRaft:
        Consenters:
        - Host: chainz1_orderer1
          Port: 6050
          ClientTLSCert: crypto-config/ordererOrganizations/chainz1/orderers/chainz1_orderer1/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/chainz1/orderers/chainz1_orderer1/tls/server.crt
        - Host: chainz1_orderer2
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/chainz1/orderers/chainz1_orderer2/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/chainz1/orderers/chainz1_orderer2/tls/server.crt
        - Host: chainz2_orderer1
          Port: 8050
          ClientTLSCert: crypto-config/ordererOrganizations/chainz2/orderers/chainz2_orderer1/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/chainz2/orderers/chainz2_orderer1/tls/server.crt
        - Host: chainz2_orderer2
          Port: 9050
          ClientTLSCert: crypto-config/ordererOrganizations/chainz2/orderers/chainz2_orderer2/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/chainz2/orderers/chainz2_orderer2/tls/server.crt

Profiles:
    TwoOrgsRaftGenesis:
        Orderer:
            <<: *raft
            Organizations:
                - *chainz1
                - *chainz2
        Consortiums:
            RaftConsortium:
                Organizations:
                    - *skcc
                    - *contractor1
    TwoOrgsRaftChannel:
        Consortium: RaftConsortium
        Application:
            Organizations:
                - *skcc
                - *contractor1

